services:
  api:
    image: wesleyalves00/pi_zambom:latest
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
      - USERS_API_URL=${USERS_API_URL}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
